scheme: "Default"
author: "Jon Q (https://jonquach.com)"

# dark
base00: "181818"
base01: "1D1D1D"
base02: "282828"
base03: "484848"

# light
base04: "B8B8B8"
base05: "E8E8E8"
base06: "F2F2F2"
base07: "F8F8F8"

base08: "ab4642"
base09: "dc9656"
base0A: "f7ca88"
base0B: "a1b56c"
base0C: "86c1b9"
base0D: "7cafc2"
base0E: "ba8baf"
base0F: "a16946"
